# Generated by Django 4.1.2 on 2022-10-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Register',
        ),
    ]
